// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5aBXgZXMfGSbWXY211Fm4-WtPjsSiuA',
    appId: '1:751094344726:web:6752b2db80abaf6e045937',
    messagingSenderId: '751094344726',
    projectId: 'books-a1007',
    authDomain: 'books-a1007.firebaseapp.com',
    storageBucket: 'books-a1007.firebasestorage.app',
    measurementId: 'G-BP9DV7MW12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_zIFXP7EPUpI0EZoBeLDcPUFrNu1xvsw',
    appId: '1:751094344726:android:252a4a56202227a6045937',
    messagingSenderId: '751094344726',
    projectId: 'books-a1007',
    storageBucket: 'books-a1007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFOEoH-5qkIEKQ1ZfzWMM50rtAWf2W_GM',
    appId: '1:751094344726:ios:9e799759d0b3626e045937',
    messagingSenderId: '751094344726',
    projectId: 'books-a1007',
    storageBucket: 'books-a1007.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFOEoH-5qkIEKQ1ZfzWMM50rtAWf2W_GM',
    appId: '1:751094344726:ios:9e799759d0b3626e045937',
    messagingSenderId: '751094344726',
    projectId: 'books-a1007',
    storageBucket: 'books-a1007.firebasestorage.app',
    iosBundleId: 'com.example.books',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh5aBXgZXMfGSbWXY211Fm4-WtPjsSiuA',
    appId: '1:751094344726:web:88ddd3fcc7de0d9a045937',
    messagingSenderId: '751094344726',
    projectId: 'books-a1007',
    authDomain: 'books-a1007.firebaseapp.com',
    storageBucket: 'books-a1007.firebasestorage.app',
    measurementId: 'G-ECK3N2WB5B',
  );
}
